---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.yaml
  - ./dashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: cnpg-dashboards
    files:
      - ./configmaps/cloudnative-pg.json
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true