---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres18
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-202604270853-standard-trixie
  storage:
    size: 30Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    extensions:
      - name: postgis
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.1-18-trixie
        ld_library_path:
          - system
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.0.0
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
    shared_preload_libraries:
      - vchord.so

  bootstrap:
    initdb: {}
